In [ ]:
!wget -q https://www.dropbox.com/s/63j3myz3hobc8cu/PASCAL_VOC.zip

In [ ]:
!unzip PASCAL_VOC.zip

Archive:  PASCAL_VOC.zip
   creating: PASCAL_VOC/
  inflating: PASCAL_VOC/pascal_test2007.json  
  inflating: PASCAL_VOC/pascal_train2007.json  
  inflating: PASCAL_VOC/pascal_train2012.json  
  inflating: PASCAL_VOC/pascal_val2007.json  
  inflating: PASCAL_VOC/pascal_val2012.json  


In [ ]:
import json
train_data = json.load(open("/content/PASCAL_VOC/pascal_train2007.json"))
train_data.keys()

dict_keys(['images', 'type', 'annotations', 'categories'])

In [ ]:
categories = [k["name"] for k in train_data["categories"]]
print(categories)

['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']


In [ ]:
import numpy as np

In [ ]:
train_data2 = {}

for k in train_data["annotations"]:
  if k["ignore"]==0:
    bb = k["bbox"]
    bb = np.array([bb[1],bb[0],bb[1]+bb[3]-1,bb[0]+bb[2]-1])
    if k["image_id"] not in list(train_data2.keys()):
      train_data2[k["image_id"]] = []
    train_data2[k["image_id"]].append((bb,k["category_id"]))

train_data2


In [ ]:
train_data2[3367]

[(array([173,   0, 252,  37]), 15),
 (array([212,  14, 301, 110]), 14),
 (array([166, 353, 266, 388]), 16),
 (array([129, 386, 169, 417]), 16),
 (array([127, 421, 170, 446]), 16),
 (array([141, 475, 172, 495]), 16)]

In [ ]:
def get_largest(b):
  out = sorted(b,key = lambda x:np.prod(x[0][-2:] - x[0][:2]),reverse=True)
  return out


In [ ]:
get_largest(train_data2[3367])

[(array([212,  14, 301, 110]), 14),
 (array([166, 353, 266, 388]), 16),
 (array([173,   0, 252,  37]), 15),
 (array([129, 386, 169, 417]), 16),
 (array([127, 421, 170, 446]), 16),
 (array([141, 475, 172, 495]), 16)]

In [ ]:
train_data3 = {}

for k in list(train_data2.keys()):
  train_data3[k] = []
  train_data3[k].append(get_largest(train_data2[k])[0])

In [ ]:
train_data3

{12: [(array([ 96, 155, 269, 350]), 7)],
 17: [(array([ 77,  89, 335, 402]), 13)],
 23: [(array([  1,   2, 461, 242]), 15)],
 26: [(array([124,  89, 211, 336]), 7)],
 32: [(array([ 77, 103, 182, 374]), 1)],
 33: [(array([106,   8, 262, 498]), 1)],
 34: [(array([166, 115, 399, 359]), 19)],
 35: [(array([ 97, 217, 317, 464]), 15)],
 36: [(array([ 78,  26, 343, 318]), 12)],
 42: [(array([ 31, 262, 294, 499]), 19)],
 44: [(array([  0,   0, 329, 369]), 9)],
 47: [(array([  0,  14, 311, 458]), 7)],
 48: [(array([  0,   1, 499, 301]), 15)],
 61: [(array([ 10, 273, 278, 436]), 4)],
 64: [(array([ 22,   0, 499, 450]), 3)],
 66: [(array([181, 241, 258, 273]), 15)],
 73: [(array([142, 120, 459, 374]), 16)],
 77: [(array([  0,   1, 332, 305]), 8)],
 78: [(array([ 74,  14, 411, 474]), 12)],
 83: [(array([ 32, 108, 308, 446]), 7)],
 89: [(array([ 50,  21, 290, 316]), 9)],
 91: [(array([240, 124, 283, 194]), 7)],
 104: [(array([  6,   1, 332, 282]), 15)],
 112: [(array([173,  69, 327, 276]), 12)],
 1

In [ ]:
categories[train_data3[3969][0][1]]

'boat'

In [ ]:
import pandas as pd

In [ ]:
data = {"file_name":list(train_data3.keys())}


df = pd.DataFrame(data)
df["category"] = [categories[train_data3[j][0][1]-1] for j in list(df["file_name"])]
df["cat_id"] = [train_data3[j][0][1] for j in list(df["file_name"])]
df["bbox"] = [train_data3[j][0][0] for j in list(df["file_name"])]
df.head()

file_name   category  cat_id                 bbox
0         12        car       7  [96, 155, 269, 350]
1         17      horse      13   [77, 89, 335, 402]
2         23     person      15     [1, 2, 461, 242]
3         26        car       7  [124, 89, 211, 336]
4         32  aeroplane       1  [77, 103, 182, 374]

In [ ]:
df.to_pickle("labels.p")
df.to_csv("labels_pascal_voc.csv")

In [ ]:
list(df["file_name"])

[12,
 17,
 23,
 26,
 32,
 33,
 34,
 35,
 36,
 42,
 44,
 47,
 48,
 61,
 64,
 66,
 73,
 77,
 78,
 83,
 89,
 91,
 104,
 112,
 122,
 129,
 133,
 134,
 138,
 140,
 141,
 147,
 153,
 154,
 159,
 161,
 162,
 163,
 164,
 171,
 173,
 174,
 187,
 189,
 192,
 193,
 194,
 198,
 200,
 207,
 209,
 219,
 220,
 222,
 225,
 228,
 235,
 242,
 250,
 256,
 259,
 262,
 263,
 276,
 278,
 282,
 288,
 294,
 296,
 306,
 307,
 311,
 312,
 317,
 320,
 325,
 331,
 334,
 337,
 344,
 347,
 349,
 355,
 359,
 367,
 370,
 372,
 379,
 382,
 387,
 391,
 394,
 395,
 400,
 404,
 406,
 407,
 411,
 416,
 430,
 431,
 438,
 446,
 450,
 454,
 463,
 468,
 469,
 470,
 474,
 476,
 477,
 484,
 489,
 496,
 503,
 508,
 516,
 518,
 519,
 522,
 524,
 525,
 526,
 528,
 535,
 537,
 541,
 544,
 549,
 550,
 552,
 554,
 555,
 559,
 565,
 577,
 583,
 589,
 590,
 592,
 597,
 605,
 609,
 612,
 620,
 622,
 625,
 632,
 633,
 635,
 648,
 654,
 657,
 671,
 672,
 680,
 685,
 688,
 689,
 695,
 699,
 700,
 709,
 710,
 711,
 726,
 729,
 731,
 733,
 7